### ISSUE TITLE
[Proposal] Add a verbose error message for saysLike and repromptsLike

### ISSUE THREAD

**Issue by s-maheshbabu** [taimos/ask-sdk-test#17]
### Description
Filing this to discuss a proposal before actually making the changes. 

```javascript
`expect(actualSay.indexOf(currentItem.saysLike) >= 0, 'Speech did not contain specified text').to.be.true;`
```

When that fails, we get a generic error message. When this happen, the developer probably wants to look at the actual and expected values. Anecdotally, I found myself temporarily changing 'saysLike' to 'says' just so I can see what the skill actually returned. 

Proposal is to change to something like the following - 
```javascript
expect(actualSay.indexOf(currentItem.saysLike) >= 0, `Speech did not contain specified text. Expected ${actualSay} to be like ${currentItem.saysLike}`).to.be.true;
```

Comments?

**Comment by hoegertn** [comment]
Sounds great. Can you open a PR?

**Comment by s-maheshbabu** [comment]
Cool. I will.
