### ISSUE TITLE
Pass Session Attributes to Test

### ISSUE THREAD

**Issue by kyle-wrenn** [taimos/ask-sdk-test#3]
It looks like the attributes object is being passed to test() as undefined.

**Comment by hoegertn** [comment]
Can you elaborate on the issue? Do you happen to have a code example that is not working?

**Comment by kyle-wrenn** [comment]
I'm trying to include session attributes under` request.session.attributes`.
In the previous version, you could using `withSessionAttributes` and pass it an object to include. In this version, it looks like the attributes object will always be set to `{}`.

**Comment by hoegertn** [comment]
Indeed, it starts with an empty session and then uses the outcome for the next call in the sequence. I will check with the v1 behavior and change this if needed. Thanks for bringing this to my attention.

**Comment by hoegertn** [comment]
released with version `2.0.2`
