### ISSUE TITLE
Simulate a device that supports video

### ISSUE THREAD

**Issue by clara-jr** [taimos/ask-sdk-test#31]
Using the condition `.withInterfaces({ video: true }).build()` to build a request does not set the `handlerInput.requestEnvelope.context.Viewport.video` to `true` in order to simulate a device that does support video. It only changes the value of `handlerInput.requestEnvelope.context.System.device.supportedInterfaces.VideoApp`.

Do you think it's possible to add something like this in the `RequestBuilder`?
```
if (this.settings.interfaces.video) {
  ctx.System.device.supportedInterfaces.VideoApp = {};
  ctx.Viewport = { video: true }
}
```

**Comment by hoegertn** [comment]
Happy to change that. Could somebody please verify this or link to docs explaining this? I want to make sure that this will always be true

**Comment by clara-jr** [comment]
I can share these links:

- https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-interface.html#viewport-object
- https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-interface.html#video

in which the `Viewport` object included in the Alexa requests and the `video` property are explained. The `Viewport` object contains information about the supported viewports for the user's device. Particularly, the `video` property would be an object including an array representing the available technologies for playing video on that device. If the device does not support playing videos, the `video` property will not be present. So I think that to simulate a device that supports playing video it's enough to make that property exist (or be _truthy_).

**Comment by hoegertn** [comment]
Sorry for the delay. Sounds reasonable. Would you be able to provide a PR for this?

**Comment by clara-jr** [comment]
Sure! Here it is:
- https://github.com/taimos/ask-sdk-test/pull/37
