### ISSUE TITLE
Provide option to pass user.accessToken along with userId

### ISSUE THREAD

**Issue by schavaLogi** [taimos/ask-sdk-test#6]
### Description
Must be able to provide option to pass user accessToken for the skill which needs mandatory linking. 

### Steps to Reproduce

1. LaunchRequest with linked account option must be able to get accessToken information

**Comment by hoegertn** [comment]
Sounds like a great idea. Can you provide the corresponding JSON snippet?

**Comment by schavaLogi** [comment]
Under user node along with userId, we will be getting accessToken
Sample:
{
"session": {
    "user": {
      "userId": "amzn1.ask.account.AET4P3LONAB3ZZYJ5HJFLLCHCFOHHOLRMXALB6DL7UBAIBDQFGLSZJDKWNZ6P56M6FBY6SFAXULD3Z343Q7YE6FMO7UHMEKUCTQTPV6KLXETFBXWB6CGOSWTHCNHHCMO5KBJFCJINJS52HWZIWCPCVHOW5OKVXHP5CCEVZ7SRUF6GJRBE5WJL2Z7D54HPXEH6QOAVZRRNU34MXY",
 "accessToken": "JWT Token",
    },
    "new": true
  },
"context": {
"user": {
        "userId": "amzn1.ask.account.AET4P3LONAB3ZZYJ5HJFLLCHCFOHHOLRMXALB6DL7UBAIBDQFGLSZJDKWNZ6P56M6FBY6SFAXULD3Z343Q7YE6FMO7UHMEKUCTQTPV6KLXETFBXWB6CGOSWTHCNHHCMO5KBJFCJINJS52HWZIWCPCVHOW5OKVXHP5CCEVZ7SRUF6GJRBE5WJL2Z7D54HPXEH6QOAVZRRNU34MXY",
        "accessToken": "JWT Token",
      },
}
}
