### ISSUE TITLE
when i debug tests using VS code, getting error "mocha_1.it is not a function"

### ISSUE THREAD

**Issue by xs2bharat** [taimos/ask-sdk-test#7]
### Description

when i debug tests using VS code, getting error "mocha_1.it is not a function"

### Steps to Reproduce

1. Configured VSCode to debug mocha tests using instructions at https://github.com/Microsoft/vscode-recipes/tree/master/debugging-mocha-tests
2. Run unit test using npm test with command "test: mocha --recursive" successfully
3. But when debugging using VSCode getting error "mocha_1.it is not a function"

**Expected behavior:** Tests should debug

**Actual behavior:** Error "mocha_1.it is not a function"no

### Environment

**NodeJS-Version:** v8.14.0

**OS:** Windows 10

**Comment by hoegertn** [comment]
Can you try if this solves the issue? https://github.com/mochajs/mocha/issues/3391#issuecomment-458834965

**Comment by xs2bharat** [comment]
I am using nodejs without type script so not sure your link will apply to me. Surprisingly as per above microsoft article, "Mocha All" profile works and debug it correctly. Only "Mocha current file" is throwing error.
